apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: test-routes
  namespace: gloo-system
spec:
  routes:
    - matchers:
      - prefix: /httpbin/
      routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system
      options:
        prefixRewrite: /
    